// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Arrow: (typeof import('./node_modules/@slidev/client/builtin/Arrow.vue'))['default'];
    AutoFitText: (typeof import('./node_modules/@slidev/client/builtin/AutoFitText.vue'))['default'];
    'Carbon:apps': (typeof import('~icons/carbon/apps'))['default'];
    'Carbon:arrowLeft': (typeof import('~icons/carbon/arrow-left'))['default'];
    'Carbon:arrowRight': (typeof import('~icons/carbon/arrow-right'))['default'];
    'Carbon:checkmark': (typeof import('~icons/carbon/checkmark'))['default'];
    'Carbon:close': (typeof import('~icons/carbon/close'))['default'];
    'Carbon:download': (typeof import('~icons/carbon/download'))['default'];
    'Carbon:edit': (typeof import('~icons/carbon/edit'))['default'];
    'Carbon:information': (typeof import('~icons/carbon/information'))['default'];
    'Carbon:logoTwitter': (typeof import('~icons/carbon/logo-twitter'))['default'];
    'Carbon:maximize': (typeof import('~icons/carbon/maximize'))['default'];
    'Carbon:minimize': (typeof import('~icons/carbon/minimize'))['default'];
    'Carbon:pen': (typeof import('~icons/carbon/pen'))['default'];
    'Carbon:presentationFile': (typeof import('~icons/carbon/presentation-file'))['default'];
    'Carbon:settingsAdjust': (typeof import('~icons/carbon/settings-adjust'))['default'];
    'Carbon:textAnnotationToggle': (typeof import('~icons/carbon/text-annotation-toggle'))['default'];
    'Carbon:userSpeaker': (typeof import('~icons/carbon/user-speaker'))['default'];
    CarbonLogoGithub: (typeof import('~icons/carbon/logo-github'))['default'];
    CarbonMoon: (typeof import('~icons/carbon/moon'))['default'];
    CarbonSun: (typeof import('~icons/carbon/sun'))['default'];
    CodeBlockWrapper: (typeof import('./node_modules/@slidev/client/builtin/CodeBlockWrapper.vue'))['default'];
    Counter: (typeof import('./components/Counter.vue'))['default'];
    LightOrDark: (typeof import('./node_modules/@slidev/client/builtin/LightOrDark.vue'))['default'];
    Link: (typeof import('./node_modules/@slidev/client/builtin/Link.vue'))['default'];
    Mermaid: (typeof import('./node_modules/@slidev/client/builtin/Mermaid.vue'))['default'];
    Monaco: (typeof import('./node_modules/@slidev/client/builtin/Monaco.vue'))['default'];
    PhCheckCircle: (typeof import('~icons/ph/check-circle'))['default'];
    PhClipboard: (typeof import('~icons/ph/clipboard'))['default'];
    PhCursorDuotone: (typeof import('~icons/ph/cursor-duotone'))['default'];
    PhCursorFill: (typeof import('~icons/ph/cursor-fill'))['default'];
    PlantUml: (typeof import('./node_modules/@slidev/client/builtin/PlantUml.vue'))['default'];
    RenderWhen: (typeof import('./node_modules/@slidev/client/builtin/RenderWhen.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SlideCurrentNo: (typeof import('./node_modules/@slidev/client/builtin/SlideCurrentNo.vue'))['default'];
    SlidesTotal: (typeof import('./node_modules/@slidev/client/builtin/SlidesTotal.vue'))['default'];
    Starport: (typeof import('vue-starport'))['Starport'];
    StarportCarrier: (typeof import('vue-starport'))['StarportCarrier'];
    Toc: (typeof import('./node_modules/@slidev/client/builtin/Toc.vue'))['default'];
    TocList: (typeof import('./node_modules/@slidev/client/builtin/TocList.vue'))['default'];
    Transform: (typeof import('./node_modules/@slidev/client/builtin/Transform.vue'))['default'];
    Tweet: (typeof import('./node_modules/@slidev/client/builtin/Tweet.vue'))['default'];
    VAfter: (typeof import('./node_modules/@slidev/client/builtin/VAfter.ts'))['default'];
    VClick: (typeof import('./node_modules/@slidev/client/builtin/VClick.ts'))['default'];
    VClicks: (typeof import('./node_modules/@slidev/client/builtin/VClicks.ts'))['default'];
    Youtube: (typeof import('./node_modules/@slidev/client/builtin/Youtube.vue'))['default'];
  }
}
