# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier

# Allow inline HTML elements within Markdown content for enhanced formatting
no-inline-html: false
