name: Release It!

on:
  push:
    branches:
      - release/[1-9][0-9]*.[1-9][0-9]*
  workflow_dispatch:
    inputs:
      release-branch-calver:
        required: false
        type: string
env:
  HUSKY: 0

jobs:
  clean-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

  release-it:
    needs: clean-install
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "Zhang Jia Rong"
          git config user.email zhang-jia-rong@outlook.com
      - run: echo -n "${GPG_PRIVATE_KEY}" | base64 --decode | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - run: git config user.signingkey ${GPG_KEY_ID}
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      - if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'develop' && github.event.inputs.release-branch-calver == '' }}
        run: git checkout -b release/$(date +'%Y.%-m')
      - if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'develop' && github.event.inputs.release-branch-calver != '' }}
        run: |
          git checkout release/${{ github.event.inputs.release-branch-calver }}
          git merge --ff-only develop
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'develop' && github.event.inputs.release-branch-calver == '' }}
        run: npm run release -- --ci --no-git.requireUpstream --npm.tag=next --github.preRelease --plugins.@csmith/release-it-calver-plugin.increment=calendar.rc
      - if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name == 'develop' && github.event.inputs.release-branch-calver != '' }}
        run: npm run release -- --ci --no-git.requireUpstream --npm.tag=next --github.preRelease --plugins.@csmith/release-it-calver-plugin.increment=minor.rc
      - if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'release/') }}
        run: npm run release -- --ci --npm.tag=next --github.preRelease --plugins.@csmith/release-it-calver-plugin.increment=rc
      - if: ${{ github.event_name == 'workflow_dispatch' && startsWith(github.ref_name, 'release/') }}
        run: npm run release -- --ci --no-git.requireCommits --plugins.@csmith/release-it-calver-plugin.increment=minor
